name: 'TestForest Dashboard'
description: 'Display test results summary in a GitHub Actions workflow'
author: 'Edward Thomson'
inputs:
  paths:
    description: Path(s) to test output file(s) to analyze
    required: true
  output:
    description: File to write with rendered output
  show:
    description: List of types of tests to show in the results table. Values are `all`, `none`, `pass`, `skip`, or `fail`.
  summary-title:
    description: Title for the summary section. If not provided, defaults to "Test failures/results or Skipped/Passing tests depending on the show input.
    default: ''
    required: false
  run-url:
    description: Optional URL to the run that generated the test results to add a hyperlink in the title.
    default: ''
    required: false
  flaky-tests-json:
    description: Path to the JSON file with flaky test information to flag them in the summary.
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: check-square
  color: green
