# Copyright (C) 2025 TomTom NV. All rights reserved.

---

name: Release and Deploy GitHub Action

concurrency: deployment

on:
  push:
    branches:
      - main

jobs:
  github-release:
    name: Release Action
    outputs:
      next-version: ${{ steps.commisery.outputs.next-version }}
    runs-on: az-weu-ubuntu-24.04-amd64-05cpu
    steps:
      - name: Generate version
        id: commisery
        uses: tomtom-international/commisery-action/bump@v3
        with:
          create-release: true
          token: ${{ github.token }}
          version-prefix: v

  release-action:
    runs-on: az-weu-ubuntu-24.04-amd64-05cpu
    needs: github-release
    if: needs.github-release.outputs.next-version != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.github-release.outputs.next-version }}

      - name: Update the ${{ needs.github-release.outputs.next-version }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ needs.github-release.outputs.next-version }}